#!/usr/bin/env bash
set -e
set -o pipefail

prog="$(basename "$0")"
archives=()
v=''

usage() {
	cat >&2 <<-EOF
	Usage: $prog [option ...] file [file ...]
	Lists the contents of archives.

	Options:
	  -h    Show this help
	  -v    Verbose archive listing
	EOF
}

exists() { hash "$1" 2>/dev/null; }
err() { printf '%s: %s\n' "$prog" "$1" >&2; }

lstar() {
	local type
	type="$(file -E -bL --mime-type "$1")"
	if (($?)); then
		err "$type"
		return 1
	fi
	case "$type" in
	'application/x-tar')
		tar t${v}f "$1" ;;
	'application/x-bzip2')
		tar t${v}jf "$1" ;;
	'application/x-gzip')
		tar t${v}zf "$1" ;;
	'application/x-lrzip')
		if bsdtar --lrzip --help &> /dev/null; then
			bsdtar --lrzip -t${v}f "$1"
		else
			lrzcat "$1" | tar t${v}f -
		fi
		;;
	'application/x-lzip')
		lzip --keep --quiet --decompress --stdout "$1" | tar t${v}f - ;;
	'application/x-lzma')
		if tar --lzma --help &> /dev/null; then
			tar --lzma -t${v}f "$1"
		else
			lzcat "$1" | tar t${v}f -
		fi
		;;
	'application/x-xz')
		if tar --xz --help &> /dev/null; then
			tar --xz -t${v}f "$1"
		else
			xzcat "$1" | tar t${v}f -
		fi
		;;
	*)
		printf "%s: cannot list: %s" "$prog" "$1" >&2
		return 1
		;;
	esac
}

lsarchive() {
	local type
	type="$(file -E -bL --mime-type "$1")"
	if (($?)); then
		err "$type"
		return 1
	fi
	case "$(file -bL --mime-type "$1")" in
	'application-x-7z-compressed')
		7za l "$1"
		;;
	'application/java-archive'|'application/zip')
		unzip -l${v} "$1"
		;;
	'application/x-rar')
		if unrar; then
			unrar -"${v:-l}" "$1"
		else
			rar -"${v:-l}" "$1"
		fi
		;;
	*)
		printf "%s: cannot list: %s (no handler for '%s')\n" \
			"$prog" "$1" "$type" >&2
		return 1
		;;
esac
}

ls() {
	local type
	type="$(file -E -bzL --mime-type "$1")"
	if (($?)); then
		err "$type"
		return 1
	fi

	case "$type" in
	'application/x-tar')
		lstar "$1"
		;;
	*)
		lsarchive "$1"
		;;
	esac
}

while (($#)); do
	case "$1" in
	-h)
		usage
		exit
		;;
	-v)
		v=v
		shift
		;;
	*)
		archives+=("$1")
		shift
		;;
	esac
done

exit_status=0

for archive in "${archives[@]}"; do
	if ! ls "$archive"; then
		exit_status=1
	fi
done

exit "$exit_status"
