#!/bin/sh

set -e

prog="$(basename "$0")"
v=''

usage() {
	cat >&2 <<-EOF
	Usage: $prog [option ...] file [file ...]
	Lists the contents of archives.

	Options:
	  -h    Show this help
	  -v    Try to be verbose
	EOF
}

exists() { hash "$1" 2>/dev/null; }
err() { printf '%s: %s\n' "$prog" "$1" 1>&2; }
errf() { fmt="$1"; shift; printf "%s: $fmt\n", "$prog" "$@" 1>&2; }

if exists bsdtar; then
	tar=bsdtar
else
	tar=tar
fi

bsdtar_list() { bsdtar -t${v}f "$1"; }
tar_list() { "$tar" -t${v}f "$1"; }

lstar() {
	type_tar="$(file -E -bL --mime-type "$1")"
	if [ "$?" != 0 ]; then
		err "$type_tar"
		return 1
	fi
	case "$type_tar" in
	'application/x-tar'|'application/x-bzip2'|'application/x-gzip')
		tar_list "$1" ;;
	'application/x-lrzip')
		if bsdtar --lrzip --help >/dev/null 2>&1; then
			bsdtar_list "$1"
		else
			lrzcat "$1" | tar_list -
		fi
		;;
	'application/x-lzip')
		lzip --keep --quiet --decompress --stdout "$1" | tar_list - ;;
	'application/x-lzma')
		if "$tar" --lzma --help >/dev/null 2>&1; then
			tar_list "$1"
		else
			lzcat "$1" | tar_list -
		fi
		;;
	'application/x-xz')
		if "$tar" --xz --help >/dev/null 2>&1; then
			tar_list "$1"
		else
			xzcat "$1" | tar_list -
		fi
		;;
	'application/x-lz4')
		lz4cat "$1" | tar_list -
		;;
	*)
		# last resort
		bsdtar_list "$1" ;;
	esac
}

lsarchive() {
	type_ar="$(file -E -bL --mime-type "$1")"
	if [ "$?" != 0 ]; then
		err "$type_ar"
		return 1
	fi
	case "$(file -bL --mime-type "$1")" in
	'application-x-7z-compressed')
		if exists 7za; then
			7za l "$1"
		else
			bsdtar_list "$1"
		fi
		;;
	'application/java-archive'|'application/zip')
		if exists bsdtar; then
			bsdtar_list "$1"
		else
			unzip -l${v} "$1"
		fi
		;;
	'application/x-rar')
		if exists unrar; then
			unrar -"${v:-l}" "$1"
		elif exists rar; then
			rar -"${v:-l}" "$1"
		else
			bsdtar_list "$1"
		fi
		;;
	*)
		errf "no handler for '%s' (%s), trying bsdtar\n" "$1" "$type_ar"
		bsdtar_list "$1"
		;;
esac
}

ls() {
	type="$(file -E -bzL --mime-type "$1")"
	if [ "$?" != 0 ]; then
		err "$type"
		return 1
	fi

	case "$type" in
	'application/x-tar')
		lstar "$1"
		;;
	*)
		lsarchive "$1"
		;;
	esac
}

while :; do
	case "$1" in
	'') break ;;
	--) shift; break ;;
	-h) usage; exit ;;
	-v) v=v; shift ;;
	-?*) printf '%s: invalid option: %s\n' "$(basename "$0")" "$1" 1>&2; exit 1 ;;
	*) break ;;
	esac
done

exit_status=0

for archive in "$@"; do
	if ! ls "$archive"; then
		exit_status=1
	fi
done

exit "$exit_status"
