#!/usr/bin/env bash
set -e
set -o pipefail

prog="$(basename "$0")"
archives=()
clobber=0

usage() {
	cat >&2 <<-EOF
	Usage: $prog [option ...] file [file ...]
	Extracts the content of archives.

	To extract in parallel, use the gnu parallel utility or xargs.

	Options:
	  -h    Show this help
	  -f    Don't try to avoid clobbering files
	EOF
}

exists() { hash "$1" 2>/dev/null; }
err() { printf '%s: %s\n' "$prog" "$1" 1>&2; }
errf() { fmt="$1"; shift; printf "%s: $fmt\n", "$prog" "$@" 1>&2; }

if exists bsdtar; then
	tar=bsdtar
else
	tar=tar
fi

bsdtar_x() { bsdtar "-x${k}vf" "$1"; }
tar_x() { "$tar" "-x${k}vf" "$1"; }

untar() {
	local type
	type="$(file -E -bL --mime-type "$1")"
	if (($?)); then
		err "$type"
		return 1
	fi
	k=k
	if ((clobber)); then
		k=''
	fi
	case "$type" in
	'application/x-tar'|'application/x-bzip2'|'application/x-gzip')
		tar_x "$1" ;;
	'application/x-lrzip')
		if bsdtar --lrzip --help &> /dev/null; then
			bsdtar_x "$1"
		else
			lrzcat "$1" | tar x${k}vf -
		fi
		;;
	'application/x-lzip')
		lzip --keep --decompress --stdout "$1" | tar x${k}vf - ;;
	'application/x-lzma')
		if "$tar" --lzma --help &> /dev/null; then
			tar_x "$1"
		else
			lzcat "$1" | tar x${k}vf -
		fi
		;;
	'application/x-xz')
		if "$tar" --xz --help &> /dev/null; then
			tar_x "$1"
		else
			xzcat "$1" | tar x${k}vf -
		fi
		;;
	*)
		# last resort
		bsdtar_x "$1" ;;
	esac
}

extract() {
	local type
	type="$(file -E -bL --mime-type "$1")"
	if (($?)); then
		err "$type"
		return 1
	fi
	case "$type" in
	'application/x-7z-compressed')
		if exists 7za; then
			7za x "$1"
		else
			bsdtar_x "$1"
		fi
		;;
	'application/java-archive'|'application/zip')
		if exists bsdtar; then
			bsdtar_x "$1"
		else
			unzip "$1" -d "$extract_dir"
		fi
		;;
	'application/x-rar')
		if exists unrar; then
			unrar x -ad "$1"
		elif exists rar; then
			rar e -ad "$1"
		else
			bsdtar_x "$1"
		fi
		;;
	'application/x-bzip2')
		bunzip2 --keep "$1" ;;
	'application/x-gzip')
		gunzip --keep "$1" ;;
	'application/x-lrzip')
		# lrunzip keeps input by default
		lrunzip "$1" ;;
	'application/x-lzip')
		lzip --decompress --keep "$1";;
	'application/x-lzma')
		unlzma --keep "$1" ;;
	'application/x-xz')
		unxz --keep "$1" ;;
	*)
		errf "no handler for '%s' (%s), trying bsdtar\n" "$1" "$type"
		bsdtar_x "$1"
		;;
	esac
}

unarchive() {
	local type
	type="$(file -E -bzL --mime-type "$1")"
	if (($?)); then
		err "$type"
		return 1
	fi
	case "$type" in
	'application/x-tar')
		untar "$1"
		;;
	*)
		extract "$1"
		;;
	esac
}

while (($#)); do
	case "$1" in
	-h)
		usage
		exit
		;;
	-c)
		clobber=1
		shift
		;;
	*)
		archives+=("$1")
		shift
		;;
	esac
done

exit_status=0

for archive in "${archives[@]}"; do
	file_name="$(basename "$archive")"
	extract_dir="${file_name%.*}"
	if ! unarchive "$archive"; then
		exit_status=1
	fi
done

exit "$exit_status"
